# Generated by Django 4.0.2 on 2022-02-04 09:16

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_habitat', models.CharField(blank=True, choices=[('Maison', 'Maison')], max_length=20, null=True, verbose_name='Type_habitat')),
                ('type_residence', models.CharField(blank=True, choices=[('residence_principale', 'residence_principale')], max_length=20, null=True, verbose_name='Type_residence')),
                ('type_propriete', models.CharField(blank=True, choices=[('Locataire', 'Locataire')], max_length=20, null=True, verbose_name='Type_propriete')),
                ('interraction', models.BooleanField(blank=True, null=True, verbose_name='permission de contact')),
                ('Surface', models.IntegerField(blank=True, default=25, null=True, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(1000)], verbose_name='surface habitat')),
                ('nbrChambre', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Nombre des Chambres')),
                ('resiliation', models.BooleanField(blank=True, null=True, verbose_name='Besoin resiliation')),
                ('Tarification', models.FloatField(blank=True, null=True, verbose_name='Tarification devis')),
                ('franchise', models.FloatField(blank=True, null=True, verbose_name='Franchise sur devis')),
            ],
            options={
                'verbose_name_plural': 'Devis',
            },
        ),
    ]
