# Generated by Django 4.0.2 on 2022-02-04 09:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_devis_prospect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='type_propriete',
        ),
        migrations.AddField(
            model_name='devis',
            name='garanties',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=49, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_proprietide',
            field=models.CharField(blank=True, choices=[('Locataire', 'Locataire')], max_length=20, null=True, verbose_name='Type_propriete'),
        ),
    ]
