# Generated by Django 4.0.2 on 2022-02-17 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0005_devis_maison_delete_devis'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis_maison',
            name='Cheminée',
            field=models.BooleanField(default=False, verbose_name='est ce il y a Cheminée'),
        ),
        migrations.AddField(
            model_name='devis_maison',
            name='Piscine',
            field=models.BooleanField(default=False, verbose_name='est ce il y a Piscine'),
        ),
        migrations.AddField(
            model_name='devis_maison',
            name='Vérnada',
            field=models.BooleanField(default=False, verbose_name='est ce il y a veranda'),
        ),
        migrations.AddField(
            model_name='devis_maison',
            name='ancien_assurence',
            field=models.BooleanField(default=False, verbose_name='avez vous ancien assurence'),
        ),
        migrations.AddField(
            model_name='devis_maison',
            name='mois_resiliation',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='mois de resiliation'),
        ),
        migrations.AlterField(
            model_name='devis_maison',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
