# Generated by Django 4.0.2 on 2022-02-18 12:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0004_rename_firstname_prospect_nom_and_more'),
        ('devis', '0006_devis_maison_cheminée_devis_maison_piscine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis_Appartement',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_prospect', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email de prospect')),
                ('ancien_assurence', models.BooleanField(default=False, verbose_name='avez vous ancien assurence')),
                ('type_residence', models.CharField(blank=True, choices=[('principale', 'principale'), ('secondaire', 'secondaire')], max_length=255, null=True, verbose_name='Type_residence')),
                ('type_propriete', models.CharField(blank=True, choices=[('Locataire', 'Locataire'), ('proprietaire', 'proprietaire'), ('proprietaire non occupant', 'proprietaire non occupant')], max_length=255, null=True, verbose_name='Type_propriete')),
                ('interraction', models.BooleanField(blank=True, null=True, verbose_name='permission de contrat')),
                ('Surface', models.IntegerField(blank=True, default=25, null=True, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(1000)], verbose_name='surface habitat')),
                ('nbrChambre', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Nombre des Chambres')),
                ('dependance', models.BooleanField(blank=True, default=False, null=True, verbose_name='depandance de residance')),
                ('surface_depandance', models.CharField(blank=True, choices=[('plus de 100 m ', 'plus de 100 m'), ('Moin de 21 m', 'Moin de 21 m'), ('entre 21 m et 100 m ', 'entre 21 m et 100 m')], default=0, max_length=255, null=True, verbose_name='surface de depandance')),
                ('garanties', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=49, null=True)),
                ('type_resiliation', models.CharField(blank=True, choices=[('demenage', 'demenage'), ('changer habitat', 'changer habitat')], max_length=255, null=True, verbose_name='type de resiliation')),
                ('nbr_resiliation', models.CharField(blank=True, choices=[('Aucun', 'Aucun'), ('un', 'un'), ('deux', 'deux'), ('Trois ou plus', 'Trois ou plus')], max_length=255, null=True, verbose_name='nombre des resiliation')),
                ('resiliation', models.BooleanField(blank=True, null=True, verbose_name='Besoin resiliation')),
                ('periode_resiliation', models.CharField(blank=True, choices=[('plus de 12 mois ', 'plus de 12 mois'), ('Moin de 12 mois', 'Moin de 12 mois')], max_length=255, null=True, verbose_name='periode de resiliation')),
                ('mois_resiliation', models.CharField(blank=True, max_length=15, null=True, verbose_name='mois de resiliation')),
                ('periode_prochaine_resiliation', models.DateField(blank=True, null=True, verbose_name='date de prochaine resiliation')),
                ('Tarification', models.FloatField(blank=True, null=True, verbose_name='Tarification devis')),
                ('franchise', models.FloatField(blank=True, null=True, verbose_name='Franchise sur devis')),
                ('prospect', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prospect.prospect', verbose_name='le proprietary de devis')),
            ],
        ),
    ]
