# Generated by Django 4.0.2 on 2022-02-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0009_rename_ancien_assurence_devis_maison_besoin_resiliation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis_maison',
            name='nbr_resiliation',
        ),
        migrations.AddField(
            model_name='devis_maison',
            name='nbr_sinistre',
            field=models.CharField(blank=True, choices=[('Aucun', 'Aucun'), ('un', 'un'), ('deux', 'deux'), ('Trois ou plus', 'Trois ou plus')], max_length=255, null=True, verbose_name='nombre des sinistre'),
        ),
    ]
