# Generated by Django 4.0.2 on 2022-02-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0012_devis_immeuble'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis_immeuble',
            name='Niveau_sous_sol',
            field=models.CharField(blank=True, choices=[('Aucun ', 'Aucun'), ('Moins de 3 Niveaux', 'Moins de 3 Niveaux'), ('3 niveauc ou plus', '3 niveauc ou plus')], max_length=255, null=True, verbose_name='niveau sous sol de l immeuble '),
        ),
        migrations.AlterField(
            model_name='devis_immeuble',
            name='Niveau_immeuble',
            field=models.CharField(blank=True, choices=[('5 niveau ou plus ', '5 niveau ou plus '), ('Entre 6 et 8 niveaux', 'Entre 6 et 8 niveaux'), ('9 niveaux ou plus', '9 niveaux ou plus')], max_length=255, null=True, verbose_name="niveau d'etage de l immeuble "),
        ),
    ]
