# Generated by Django 4.0.2 on 2022-03-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0013_devis_immeuble_niveau_sous_sol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis_immeuble',
            name='Surface',
        ),
        migrations.AlterField(
            model_name='devis_immeuble',
            name='type_batiment',
            field=models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Standing', 'Standing')], max_length=255, null=True, verbose_name='Type_batiment'),
        ),
    ]
