# Generated by Django 4.0.2 on 2022-03-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0014_remove_devis_immeuble_surface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis_maison',
            name='adresse',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="adresse de l'immeuble"),
        ),
        migrations.AddField(
            model_name='devis_maison',
            name='complement',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="complement d'adresse "),
        ),
    ]
