# Generated by Django 4.0.2 on 2022-03-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0015_devis_maison_adresse_devis_maison_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis_appartement',
            name='adresse',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="adresse de l'immeuble"),
        ),
        migrations.AddField(
            model_name='devis_appartement',
            name='complement',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="complement d'adresse "),
        ),
        migrations.AddField(
            model_name='devis_immeuble',
            name='adresse',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="adresse de l'immeuble"),
        ),
        migrations.AddField(
            model_name='devis_immeuble',
            name='complement',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="complement d'adresse "),
        ),
    ]
