# Generated by Django 4.0.2 on 2022-03-01 21:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0016_devis_appartement_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis_immeuble',
            name='activite_commerciale',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Aucun', 'Aucun'), ('un', 'un'), ('deux', 'deux'), ('Trois ou plus', 'Trois ou plus')], max_length=355, null=True),
        ),
    ]
