# Generated by Django 4.0.2 on 2022-03-01 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0017_alter_devis_immeuble_activite_commerciale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis_immeuble',
            name='surface_immeuble',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Surface Immeuble'),
        ),
    ]
