# Generated by Django 4.0.2 on 2022-02-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(blank=True, max_length=30, null=True, verbose_name='Prénom')),
                ('LastName', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nom')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Habitat', models.CharField(blank=True, max_length=255, null=True)),
                ('add_date', models.DateField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
        ),
    ]
