# Generated by Django 4.0.2 on 2022-02-04 09:52

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='reminded',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='remided times'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
