# Generated by Django 4.0.2 on 2022-02-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0003_rename_habitat_prospect_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='FirstName',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='prospect',
            old_name='LastName',
            new_name='prenom',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='Email',
        ),
        migrations.AddField(
            model_name='prospect',
            name='adresse_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
