# Generated by Django 4.0.2 on 2022-02-18 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0004_rename_firstname_prospect_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
