# Generated by Django 4.0.2 on 2022-02-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0006_alter_prospect_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='date_naissance',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
