# Generated by Django 4.0.2 on 2022-02-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0007_prospect_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
