# Generated by Django 4.0.2 on 2022-02-21 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0008_alter_prospect_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
