# Generated by Django 4.0.2 on 2022-02-21 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0009_alter_prospect_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
